name: Create release

on:
  workflow_dispatch:
    inputs:
      path:
        type: choice
        description: Select the VERSION file to modify
        options:
        - ./VERSION
        - ./subproject/VERSION
      release-type:
        type: choice
        description: The type of release
        options:
        - patch
        - minor
        - major
      pre-release-label:
        type: string
        description: Pre-release label

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: version
        uses: dinosu-actions/semver-bump@v1.0
        with:
          path: "${{ github.event.inputs.path }}"
          release-type: ${{ github.event.inputs.release-type }}
          pre-release: ${{ github.event.inputs.pre-release-label }}
      - name: print
        run: |
          echo "previous version is ${{ steps.version.outputs.previous-version }}" 
          echo "new version is ${{ steps.version.outputs.version }}" 
      - name: update version
        run: |
          printf "${{ steps.version.outputs.version }}" > "${{ github.event.inputs.path }}"
          git add "${{ github.event.inputs.path }}"
          git config user.name 'GitHub Action'
          git config user.email '2027679+andrew-su@users.noreply.github.com'
          git commit -m 'Create release version ${{ steps.version.outputs.version }}'
          git push
  tests:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v2
      - run: |
          cat VERSION
