name: SRP

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  migrate-image:
    runs-on: ubuntu-latest
    outputs: {}
    steps:

    - name: blah
      run: |
        echo ${{ github.event_name }}
        
