name: SRP

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  migrate-image:
    runs-on: ubuntu-latest
    outputs: {}
    steps:

    - name: copy image
      run: |
        export GITHUB_FQDN=$(echo "${GITHUB_SERVER_URL}" | sed -e "s/^https:\/\///")
        export SRP_UID="uid.obj.build.github(instance='${GITHUB_FQDN}',namespace='${GITHUB_REPOSITORY}',ref='${GITHUB_REF}',action='${GITHUB_ACTION}',build_id='${GITHUB_RUN_ID}_${GITHUB_RUN_ATTEMPT}')"

        echo $SRP_UID
        echo =========
        echo uid.mtd.provenance_2_5.fragment(obj_uid=$SRP_UID)
      env:
        DEST_IMAGE: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}/nodejs-function-buildpack
        SRC_IMAGE: quay.io/boson/faas-stack-build
        TAG_FILTER: nodejs-
